Sprint 2/feat notification item
CodePartnersTeam/FOCCUS-web-app pull request #54
Opened 2024-02-08 15:33 UTC by LucasChanquia

### Resumen

👉  Se actualizó el componente para integrar el componente TimeStamp

### Detalles de los cambios

👉  Se realiza con éxito el cambio

### Checklist

👇
- [Implementar https://github.com/CodePartnersTeam/FOCCUS-web-app/issues/23 ] 

### Referencias

👉https://github.com/CodePartnersTeam/FOCCUS-web-app/issues/21

### Screensshots o documentos

2024-02-09 01:40 UTC, devEstivenValencia requested changes
@LucasChanquia revisa porfavor lo siguiente

2024-02-09 01:40 UTC, devEstivenValencia commented on src/app/components/NotificationCenter/components/Notification.Item.tsx
Si no vas a usar esos `import` no los comentes, eliminalos

2024-02-09 01:40 UTC, devEstivenValencia commented on src/app/components/NotificationCenter/components/Notification.Item.tsx
> +import { EllipsesDropdown, EllipsesGroup, EllipsesItem } from '../../_Dropdown/Ellipses'
Utiliza importacion de alias (importacion relativa) no absoluta.

Para conocer los alias disponibles revisa `tsconfig.json`

2024-02-09 01:40 UTC, devEstivenValencia commented on src/app/components/NotificationCenter/components/Notification.Item.tsx
> +				{/* // TODO: format está hardcodeado. Hay que solucionar que llegue del back */}
El formato se aplica en el Frontend el unico formato en el Backend es `YYYY-MM-DDTHH:mm:ss.sssZ`

Consulta mas sobre esto aqui 👉 [Link al articulo](https://www.notion.so/codepartners/Formatos-de-fechas-9cdc1363a2ea488a849c52831dd43391?pvs=4)

2024-02-12 19:21 UTC, LucasChanquia commented on src/app/components/NotificationCenter/components/Notification.Item.tsx
Listo

2024-02-12 19:27 UTC, LucasChanquia commented on src/app/components/NotificationCenter/components/Notification.Item.tsx
> +				{/* // TODO: format está hardcodeado. Hay que solucionar que llegue del back */}
perfecto Estiven. Ahí borro el comentario

2024-02-15 00:37 UTC, devEstivenValencia approved these changes
Aprobado ✅

2024-02-15 00:37 UTC, merged